title: DEVTOPIA
logo: /assets/img/logo.png
description: Anyone can be anything
google_analytics: UA-121865566-1
theme: jekyll-theme-minimal
social:
  facebook: https://www.facebook.com/devtopia84
  github: https://github.com/devtopia84
  instagram: https://www.instagram.com/hi.seungho